postgres:
    image: postgres
    ports:
        - "5432"
    volumes:
        - ./postgres/data:/var/lib/postgresql/data

php:
    image: nerdzeu/docker-php
    ports:
        - "9000"
    links:
        - postgres
    volumes:
        - ./php/env:/srv/http
        - ./php/conf:/etc/php

nginx:
    image: nerdzeu/docker-nginx
    ports:
        - "2337:80"
        - "2338:443"
    links:
        - php
    volumes_from:
        - php
    volumes:
        - ./nginx/conf:/etc/nginx

camo:
    image: nerdzeu/docker-camo
    #build: ./camo
    ports:
        - "8081:8081"
    links:
        - nginx
    volumes:
        - ./camo:/home/camo

redis:
    image: redis
    expose:
        - "6379"
    volumes:
        - ./redis:/data

nerdzcrush:
    image: nerdzeu/docker-nerdzcrush
    #build: .
    ports:
        - "8181:81"
    links:
        - redis
    volumes:
        - ./mediacrush:/home/mediacrush

