db:
    image: postgres
    ports:
        - "5432"

php:
    build: php
    ports:
        - "9000"
    links:
        - db
    volumes:
        - php/env:/srv/http

nginx:
    build: nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - php
    volumes:
        - nginx/conf:/etc/nginx
        - php/env:/srv/http
