postgres:
    image: postgres
    ports:
        - "5432"
redis:
    image: redis
    ports:
        - "6379"

php:
    build: php
    ports:
        - "9000"
    links:
        - postgres
        - redis
    volumes:
        - php/env:/srv/http

nginx:
    build: nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - php
    volumes:
        - nginx/conf:/etc/nginx
        - php/env:/srv/http
