postgres:
    image: postgres
    ports:
        - "5432"
    volumes:
        - postgres/data:/var/lib/postgresql/data

redis:
    image: redis
    ports:
        - "6379"

php:
    image: nerdzeu/docker-php
    ports:
        - "9000"
    links:
        - postgres
        - redis
    volumes:
        - php/env:/srv/http

nginx:
    image: nerdzeu/docker-nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - php
    volumes_from:
        - php
    volumes:
        - nginx/conf:/etc/nginx
